version: '3.8'

services:
  pinecone-local:
    image: ghcr.io/pinecone-io/pinecone-local:latest
    container_name: pinecone-local
    ports:
      - "5081:5081" # Expose only the necessary port
    environment:
      - PORT=5081
    platform: linux/amd64
    networks:
      - rag_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5081/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      pinecone-local:
        condition: service_healthy
    networks:
      - rag_network
    restart: unless-stopped
    environment:
      # OLLAMA_HOST should point to your host machine where Ollama is running natively
      # For Docker Desktop (macOS/Windows), use 'host.docker.internal'
      # For Linux, you might need to find your host's IP address or use '172.17.0.1' (Docker bridge IP)
      - OLLAMA_HOST=http://host.docker.internal:11434
      - PINECONE_HOST=http://pinecone-local:5081
      - PINECONE_API_KEY=pclocal
    command: streamlit run app.py

networks:
  rag_network:
    driver: bridge
