version: '3.8'

services:
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  pinecone-local:
    build:
      context: ./pinecone-local
      dockerfile: Dockerfile
    container_name: pinecone-local
    ports:
      - "5081-6000:5081-6000"
    environment:
      - PORT=5081
      - PINECONE_HOST=localhost
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5081/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  streamlit-app:
    build:
      context: ./streamlit-app
      dockerfile: Dockerfile
    container_name: streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      ollama:
        condition: service_healthy
      pinecone-local:
        condition: service_healthy
    restart: unless-stopped

volumes:
  ollama_data:
